# Generated by Django 5.0.7 on 2024-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=60)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("population", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": "weather_cities",
            },
        ),
    ]
